name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Node.jsをインストール
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'
      - name: 依存関係のインストール
        run: npm install
      - name: テストの実行
        run: npm test